mysite/autoservice/urls.py
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path('', views.index, name="index"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('uzsakymai/', views.UzsakymaiListView.as_view(), name="uzsakymai"),
    path('profilis/', views.profilis, name='profilis'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('uzsakymai/<int:pk>', views.UzsakymaiDetailView.as_view(), name='uzsakymas'),
    path('automobiliai/', views.automobiliai, name="automobiliai"),
    path('automobiliai/<int:automobilis_id>', views.automobilis, name="automobilis"),
    path('search/', views.search, name = "search"),
    path('register/', views.register, name='register'),
    path('manouzsakymai/', views.UserUzsakymaiListView.as_view(), name="manouzsakymai"),
    path('manouzsakymai/new/', views.UserUzsakymasCreateView.as_view(), name='newuzsakymas'),
    path('uzsakymai/<int:pk>/update', views.UserUzsakymasUpdateView.as_view(), name='updateuzsakymas'),
    path('uzsakymai/<int:pk>/delete', views.UserUzsakymasDeleteView.as_view(), name='deleteuzsakymas'),
    path('uzsakymai/<int:pk>/addeilute', views.UserUzsakymoEiluteCreateView.as_view(), name='addeilute'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autoservice/', include("autoservice.urls")),
    path('', include("autoservice.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/autoservice/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _


# Create your models here.

class AutomobilioModelis(models.Model):
    marke = models.CharField(_("Make"), max_length=200, help_text="Automobilio marke")
    modelis = models.CharField(_("Model"), max_length=200, help_text="Automobilio modelis")

    def __str__(self):
        return f"{self.marke} {self.modelis}"

    class Meta:
        verbose_name = _("Car model")
        verbose_name_plural = _("Car models")


class Automobilis(models.Model):
    valstybinis_nr = models.CharField(_("License plate"), max_length=200, help_text="Valstybinis numeris")
    automobilis = models.ForeignKey("AutomobilioModelis", on_delete=models.SET_NULL, null=True)
    vin_kodas = models.CharField(_("VIN code"), max_length=200, help_text="VIN kodas")
    klientas = models.CharField(_("Customer"), max_length=200, help_text="Klientas")
    cover = models.ImageField(_('Picture'), upload_to='foto', null=True, blank=True)
    aprasymas = HTMLField(null = True, blank = True)
    def __str__(self):
        return f"{self.automobilis} {self.valstybinis_nr}"

    class Meta:
        verbose_name = _("Car")
        verbose_name_plural = _("Cars")


class Uzsakymas(models.Model):
    data = models.DateTimeField(_("Date"), null=True, blank=True)
    automobilis = models.ForeignKey("Automobilis", on_delete=models.CASCADE)
    vartotojas = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    grazinimo_data = models.DateField(_("Return date"), null = True, blank=True)

    def is_overdue(self):
        return self.grazinimo_data and date.today() > self.grazinimo_data

    STATUSAS = (
        ('a', _('Done')),
        ('p', _('Accepted')),
        ('v', _('In progress')),
        ('t', _('Canceled')),
    )
    statusas = models.CharField(max_length=1, choices=STATUSAS, default="p", blank=True, help_text="Statusas")

    def display_suma(self):
        sum = 0
        for eilute in self.eilutes.all():
            sum += eilute.display_kaina()
        return sum

    display_suma.short_description = _('Total')

    def __str__(self):
        return f"{self.automobilis}"

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")


class Paslauga(models.Model):
    pavadinimas = models.CharField(_("Name"), max_length=200, help_text="Paslaugos pavadinimas")
    kaina = models.DecimalField(_("Price"), decimal_places=2, max_digits=100)

    def __str__(self):
        return f"{self.pavadinimas}"

    class Meta:
        verbose_name = _("Service")
        verbose_name_plural = _("Services")


class UzsakymoEilute(models.Model):
    paslauga = models.ForeignKey("Paslauga", on_delete=models.CASCADE)
    uzsakymas = models.ForeignKey("Uzsakymas", on_delete=models.CASCADE, related_name="eilutes")
    kiekis = models.IntegerField(_("Amount"), help_text="Kiekis")

    def display_kaina(self):
        return self.kiekis * self.paslauga.kaina

    display_kaina.short_description = _('Price')

    def __str__(self):
        return f"{self.uzsakymas} {self.paslauga}"

    class Meta:
        verbose_name = _("Order line")
        verbose_name_plural = _("Order lines")


class UzsakymoReview(models.Model):
    uzsakymas = models.ForeignKey('Uzsakymas', on_delete=models.SET_NULL, null=True, blank=True, related_name="reviews")
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField(_('Review'), max_length=2000)

    class Meta:
        verbose_name = _("Review")
        verbose_name_plural = _('Reviews')
        ordering = ['-date_created']

class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profilis")
    foto = models.ImageField(default="default.png", upload_to="profile_pics", null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.foto.path)
        if img.height > 150 or img.width > 150:
            output_size = (150, 150)
            img.thumbnail(output_size)
            img.save(self.foto.path)

    def __str__(self):
        return _("%s profile") %self.user.username
    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

mysite/autoservice/forms.py
from .models import UzsakymoReview, Profilis, Uzsakymas
from django import forms
from django.contrib.auth.models import User

class UzsakymoReviewForm(forms.ModelForm):
    class Meta:
        model = UzsakymoReview
        fields = ('content', 'uzsakymas', 'reviewer',)
        widgets = {'uzsakymas': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['foto']

class DateInput(forms.DateInput):
    input_type = 'date'

class UserUzsakymasCreateForm(forms.ModelForm):
    class Meta:
        model = Uzsakymas
        fields = ['data', 'automobilis']
        widgets = {'data': DateInput()}

mysite/autoservice/views.py
from django.shortcuts import reverse, redirect, render, get_object_or_404
from django.http import HttpResponse
from .forms import UzsakymoReviewForm, UserUpdateForm, ProfilisUpdateForm, UserUzsakymasCreateForm
from django.views import generic
from django.views.generic.edit import FormMixin
from .models import *
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _
import datetime


# Create your views here.

def index(request):
    paslaugu_kiekis = Paslauga.objects.count()
    uzsakymu_kiekis = Uzsakymas.objects.count()
    atlikti_uzsakymai = Uzsakymas.objects.filter(statusas__exact="a").count()
    automobiliu_kiekis = Automobilis.objects.count()
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    informacija = {
        'paslaugu_kiekis': paslaugu_kiekis,
        'uzsakymu_kiekis': uzsakymu_kiekis,
        'atlikti_uzsakymai': atlikti_uzsakymai,
        'automobiliu_kiekis': automobiliu_kiekis,
        "vizitai": num_visits,
    }
    return render(request, 'index.html', context=informacija)


def automobiliai(request):
    paginator = Paginator(Automobilis.objects.all(), 1)
    page_number = request.GET.get("page")
    automobiliai = paginator.get_page(page_number)
    context = {
        "automobiliai": automobiliai
    }
    return render(request, "automobiliai.html", context=context)


def automobilis(request, automobilis_id):
    automobilis = get_object_or_404(Automobilis, pk=automobilis_id)
    return render(request, "automobilis.html", {"automobilis": automobilis})


class UzsakymaiListView(generic.ListView):
    model = Uzsakymas
    paginate_by = 1
    template_name = "uzsakymai.html"
    context_object_name = "uzsakymai"


class UserUzsakymasCreateView(LoginRequiredMixin, generic.CreateView):
    model = Uzsakymas
    # fields = ['data', 'automobilis']
    success_url = "/autoservice/manouzsakymai/"
    template_name = 'usernewuzsakymas.html'
    form_class = UserUzsakymasCreateForm

    def form_valid(self, form):
        form.instance.vartotojas = self.request.user
        form.instance.grazinimo_data = form.instance.data + datetime.timedelta(days=7)
        return super().form_valid(form)


class UserUzsakymoEiluteCreateView(LoginRequiredMixin, generic.CreateView):
    model = UzsakymoEilute
    fields = ['paslauga', 'kiekis']
    template_name = 'addeilute.html'

    def get_success_url(self):
        return reverse('uzsakymas', args=(self.object.uzsakymas.id,))

    def form_valid(self, form):
        form.instance.uzsakymas = Uzsakymas.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)


class UserUzsakymasUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Uzsakymas
    # fields = ['data', 'automobilis']
    success_url = "/autoservice/manouzsakymai/"
    template_name = 'usernewuzsakymas.html'
    form_class = UserUzsakymasCreateForm

    def form_valid(self, form):
        form.instance.vartotojas = self.request.user
        form.instance.grazinimo_data = form.instance.data + datetime.timedelta(days=7)
        return super().form_valid(form)

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.vartotojas


class UserUzsakymasDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Uzsakymas
    success_url = "/autoservice/manouzsakymai/"
    template_name = 'deleteuzsakymas.html'

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.vartotojas


class UserUzsakymaiListView(LoginRequiredMixin, generic.ListView):
    model = Uzsakymas
    paginate_by = 2
    template_name = "useruzsakymai.html"
    context_object_name = "useruzsakymai"

    def get_queryset(self):
        return Uzsakymas.objects.filter(vartotojas=self.request.user)


class UzsakymaiDetailView(FormMixin, generic.DetailView):
    model = Uzsakymas
    template_name = "uzsakymas.html"
    context_object_name = "uzsakymas"
    form_class = UzsakymoReviewForm

    def get_success_url(self):
        return reverse("uzsakymas", kwargs={"pk": self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.uzsakymas = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(UzsakymaiDetailView, self).form_valid(form)


def search(request):
    query = request.GET.get('query')
    search_results = Automobilis.objects.filter(
        Q(klientas__icontains=query) | Q(automobilis__marke__icontains=query) | Q(
            automobilis__modelis__icontains=query) | Q(vin_kodas__icontains=query) | Q(valstybinis_nr__icontains=query))
    return render(request, 'search.html', {'automobiliai': search_results, 'query': query})


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request,  _('Username %s already exists!') % username)
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _('Email %s already exists!') % email)
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, _('Registration completed!'))
                    return redirect('login')
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'register.html')


@login_required
def profilis(request):
    return render(request, 'profilis.html')


@login_required
def editprofile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, _('Profile updated'))
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'editprofile.html', context)

mysite/autoservice/templates/addeilute.html
{% extends "base.html" %}
{% block title%}Uzsakymo eilute{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Nauja uzsakymo eilute</legend>
            {{ form|crispy }}
        </fieldset>
        <br/>
        <div class="form-group">
            <button class="btn btn-outline-dark" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/autoservice/templates/automobiliai.html
{% extends "base.html" %}

{% block title %}Automobiliai{% endblock %}

{% block content %}
{% load static %}
<h2>Automobiliai</h2>
<p>Siuo metu turimi automobiliai:</p>
<ul>
    {% for automobilis in automobiliai %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div>
            {% if automobilis.cover %}
            <img src="{{ automobilis.cover.url }}" class="card-img-top" alt="...">
            {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
        </div>
    </div>
    <li><a href="{% url 'automobilis' automobilis.id %}">{{automobilis}}</a></li>
    {% endfor %}
</ul>
<div class="container">
    <nav aria-label="...">
        {% if automobiliai.has_other_pages %}
        <ul class="pagination pagination-sm">
            {% for i in automobiliai.paginator.page_range %}
            {% if automobiliai.number == i %}
            <li class="page-item active">
                <a class="page-link">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

mysite/autoservice/templates/automobilis.html
{% extends "base.html" %}

{% block title %}Automobilis{% endblock %}

{% block content %}
{% load static %}
<h2>Automobilio informacija</h2>
<div class="col-md-4 d-flex align-items-stretch">
    <div>
        {% if automobilis.cover %}
        <img src="{{ automobilis.cover.url }}" class="card-img-top" alt="...">
        {% else %}
        <img src="{% static 'img/no-image.png' %}" class="card-img-top">
        {% endif %}
    </div>
</div>
<p><b>Savininkas:</b> {{ automobilis.klientas }}</p>
<p><b>Modelis:</b> {{ automobilis.automobilis }}</p>
<p><b>Valstybinis numeris:</b> {{ automobilis.valstybinis_nr }}</p>
<p><b>VIN kodas:</b> {{ automobilis.vin_kodas }}</p>
{% if automobilis.aprasymas %}
<p><b>Aprasymas:</b> {{ automobilis.aprasymas | safe}}</p>
{% endif %}
{% endblock %}

mysite/autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="p-2 bg-black text-white text-center">
    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-car-front-fill"
         viewBox="0 0 16 16">
        <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679c.033.161.049.325.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.807.807 0 0 0 .381-.404l.792-1.848ZM3 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2ZM6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2H6ZM2.906 5.189a.51.51 0 0 0 .497.731c.91-.073 3.35-.17 4.597-.17 1.247 0 3.688.097 4.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 11.691 3H4.309a.5.5 0 0 0-.447.276L2.906 5.19Z"/>
    </svg>
    <h3>Autoservisas</h3>

</div>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'uzsakymai' %}">Uzsakymai</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'automobiliai' %}">Automobiliai</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'manouzsakymai' %}">Mano uzsakymai</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'newuzsakymas' %}?next=/autoservice">Naujas
                    uzsakymas</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next=/autoservice">Atsijungti</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registruotis</a></li>
                {% endif %}

            </ul>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0 d-flex">
                <input name="query" class="form-control me-2" type="text" placeholder="Paieska">
                <button class="btn btn-outline-light" type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>
            </form>
        </div>
    </div>
</nav>
<div class=" p-3 col-sm-8 ">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}"
         role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
</div>
{% load i18n %}
<footer>
    <div class="mt-2 p-2 bg-dark text-white text-center">
        <p>© 2023 Autoserviselis </p>
        <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}"/>
            <select name="language" onchange="this.form.submit()">
                {% load static %}
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% for lang in LANGUAGES %}
                <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
                    {{ lang.1 }}
                </option>
                {% endfor %}
            </select>
        </form>
    </div>
</footer>


</body>
</html>

mysite/autoservice/templates/deleteuzsakymas.html
{% extends "base.html" %}
{% block title %}Uzsakymo trynimas{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti uzsakyma</legend>
            <h4>Ar tikrai norite ištrinti uzsakyma {{ uzsakymas }}?</h4>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'uzsakymas' uzsakymas.id %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/autoservice/templates/search.html
{% extends "base.html" %}

{% block title %}Paieska{% endblock %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if automobiliai %}
  <ul>
    {% for automobilis in automobiliai %}
      <li>
        <a href="{% url 'automobilis' automobilis.id %}">{{ automobilis }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

mysite/autoservice/templates/uzsakymas.html
{% extends "base.html" %}

{% block title %}Uzsakymai{% endblock %}

{% block content %}
<h2>Uzsakymo informacija</h2>
{% if uzsakymas.vartotojas == user %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'updateuzsakymas' uzsakymas.id %}">Redaguoti</a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'deleteuzsakymas' uzsakymas.id %}">Ištrinti</a>
</div>
{% endif %}
<p><b>Data:</b> {{ uzsakymas.data }}</p>
<p><b>Automobilis:</b><a href="{% url 'automobilis' uzsakymas.automobilis.id %}">{{ uzsakymas.automobilis }}</a></p>
<p><b>Savininkas:</b> {{ uzsakymas.automobilis.klientas }}</p>
<p><b>Statusas:</b><span
        class="{% if uzsakymas.statusas == 'a' %}text-success{% elif uzsakymas.status == 't' %}text-danger{% else %}text-warning{% endif %}"> {{ uzsakymas.get_statusas_display }} </span>
</p>
{% if uzsakymas.vartotojas == user %}
<div>
    <a class="btn btn-dark btn-sm mt-1 mb-1" href="{% url 'addeilute' uzsakymas.id %}">Prideti uzsakymo eilute</a>
</div>
{% endif %}
<table class="table table-bordered table-sm">
    <thead>
    <tr>
        <th><b>Paslauga</b></th>
        <th><b>Paslaugos kaina</b></th>
        <th><b>Kiekis</b></th>
        <th><b>Suma</b></th>
    </tr>
    </thead>
    <tbody>
    {% for eilute in uzsakymas.eilutes.all %}
    <tr>
        <td>{{eilute.paslauga}}</td>
        <td>{{eilute.paslauga.kaina}}</td>
        <td>{{eilute.kiekis}}</td>
        <td>{{eilute.display_kaina}}</td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan=3><b>Bendra suma:</b></td>
        <td>{{ uzsakymas.display_suma }}</td>
    </tr>
    </tbody>
</table>
</br>
<h4>Atsiliepimai:</h4>
{% if uzsakymas.reviews.all %}
{% for review in uzsakymas.reviews.all %}
<hr>
<strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
<p>{{ review.content }}</p>
{% endfor %}
{% else %}
<p>Uzsakymas neturi atsiliepimų</p>
{% endif %}
{% if user.is_authenticated %}
<div class="fieldWrapper">
    <hr>
    <br/>
    <h4>Palikite atsiliepimą:</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.content }}</br>
        <input type="submit" value="Išsaugoti">
    </form>
</div>
{% endif %}
{% endblock %}